// App
export const SET_IS_MOBILE = 'app/SET_IS_MOBILE';
export const APP_LOADING = 'app/APP_LOADING';

// User
export const FETCH_USER = 'user/FETCH';
export const LOADING_USER = 'user/LOADING';
export const SET_ANONYMOUS = 'user/SET_ANONYMOUS';
export const LOADING_FACEBOOK_LOGIN = 'user/LOADING_FACEBOOK_LOGIN';
export const LOADING_EMAIL_LOGIN = 'user/LOADING_EMAIL_LOGIN';
export const LOADING_EMAIL_SIGN_UP = 'user/LOADING_EMAIL_SIGN_UP';
export const LOADING_RESET_PASSWORD = 'user/LOADING_RESET_PASSWORD';
export const LOADING_SIGN_OUT = 'user/LOADING_SIGN_OUT';
export const REGISTER_USER_LOADING = 'user/REGISTER_USER_LOADING';
export const GET_USER_PROFILE_LOADING = 'user/GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE = 'user/GET_USER_PROFILE';
export const UPDATE_USER_PROFILE_LOADING = 'user/UPDATE_USER_PROFILE_LOADING';
export const UPDATE_USER_PROFILE_IMAGE_LOADING = 'user/UPDATE_USER_PROFILE_IMAGE_LOADING';
export const FETCH_USER_CREDIT_CARD_LOADING = 'user/FETCH_USER_CREDIT_CARD_LOADING';
export const DELETE_USER_CREDIT_CARD_LOADING = 'user/DELETE_USER_CREDIT_CARD_LOADING';

